spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: root
  flyway:
    locations: classpath:db/migration
    validateMigrationNaming: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
#flyway:
#  url: ${spring.datasource.url}
#  schemas: restaurant
#  user: ${spring.datasource.username}
#  password: ${spring.datasource.password}
#  locations: filesystem:src/main/resources/db/migration/
#  baseline-on-migrate: true
#  enabled: true
#  validateMigrationNaming: true
